version: '3.7'
services:
  slot_checker:
    build: .
    image: slot_checker
    # environment:
    #   - SLOT_CHECKER_DEBUG=1
    volumes:
        - /home/manue/projets/new42_slot_checker:/usr/src/app
    restart: always
